namespace NINA.Plugin.QualitySessionMeter.Core;

internal static class WebDashboardPage {
    public const string Html = """
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<meta name="theme-color" content="#0b0d10">
<title>QualitySessionMeter</title>
<style>
:root{color-scheme:dark;--bg:#0b0d10;--card:#15191f;--card2:#101419;--line:#38414c;--grid:#2c343e;--muted:#b2bbc7;--text:#f4f6f9;--blue:#8ab4f8;--green:#81c995;--yellow:#fdd663;--red:#f28b82;--purple:#c58af9}
*{box-sizing:border-box}html,body{min-height:100%;background:var(--bg)}body{margin:0;color:var(--text);font:14px/1.45 Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif;background:radial-gradient(circle at 15% -10%,#182133 0,transparent 34%),var(--bg)}
.wrap{width:min(1320px,100%);margin:auto;padding:18px}.top{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:16px}.brand h1{margin:0;font-size:22px;letter-spacing:-.02em}.brand div{color:var(--muted);font-size:12px}.live{display:flex;align-items:center;gap:7px;color:var(--green);font-size:12px}.dot{width:8px;height:8px;border-radius:50%;background:currentColor;box-shadow:0 0 12px currentColor}
.grid{display:grid;grid-template-columns:repeat(12,1fr);gap:12px}.card{background:linear-gradient(180deg,#181d23,#12161b);border:1px solid var(--line);border-radius:14px;padding:15px;min-width:0}.summary{grid-column:span 2}.summary .n{font-size:27px;font-weight:760;letter-spacing:-.04em}.label{color:var(--muted);font-size:11px;text-transform:uppercase;letter-spacing:.08em}.current{grid-column:span 5}.preview{grid-column:span 7;min-height:280px;display:flex;flex-direction:column}.guide,.timeline,.history,.glossary{grid-column:1/-1}.row{display:flex;justify-content:space-between;gap:14px;padding:6px 0;border-bottom:1px solid #29313a}.row:last-child{border:0}.row span:first-child{color:var(--muted)}.row strong{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.status{display:inline-flex;padding:4px 8px;border-radius:999px;font-weight:700;font-size:11px;letter-spacing:.04em;background:#242b34}.accepted{color:var(--green);background:#18271f}.rejected{color:var(--red);background:#301d1f}.warning{color:var(--yellow);background:#2d2819}.learning{color:var(--blue);background:#192536}.error{color:var(--red);background:#301d1f}.section-head{display:flex;align-items:center;gap:7px;margin-bottom:8px}.section-title{font-size:14px;font-weight:700}.muted{color:var(--muted)}.info{width:18px;height:18px;border-radius:50%;border:1px solid #596574;background:#11161b;color:#d7dde5;font:700 11px/16px system-ui;padding:0;cursor:pointer}.info:focus-visible{outline:2px solid var(--blue);outline-offset:2px}.chart-note{color:var(--muted);font-size:11px;margin:-2px 0 7px}.mini-legend{display:flex;flex-wrap:wrap;gap:12px;color:var(--muted);font-size:11px;margin:2px 0 5px}.swatch{display:inline-block;width:13px;height:2px;vertical-align:middle;margin:0 5px 3px 0}.glossary details{border-top:1px solid #29313a;padding:9px 0}.glossary details:first-child{border-top:0}.glossary summary{cursor:pointer;font-weight:650}.glossary p{color:var(--muted);margin:6px 0 0;max-width:1050px}.help-pop{position:fixed;z-index:30;display:none;max-width:min(430px,calc(100vw - 28px));padding:11px 12px;border:1px solid #5a6674;border-radius:9px;background:#090c10f2;color:#f4f6f9;box-shadow:0 12px 34px #000b;font-size:12px;line-height:1.5}
#preview{width:100%;height:100%;min-height:240px;object-fit:contain;border-radius:10px;background:#090b0e;margin-top:10px;border:1px solid #29313a}.chart-wrap{position:relative;width:100%;overflow:hidden}.chart-tip{position:absolute;display:none;z-index:5;pointer-events:none;max-width:350px;padding:8px 10px;border-radius:8px;background:#080a0df2;border:1px solid #586473;color:#f3f6f9;font-size:11px;line-height:1.5;box-shadow:0 8px 28px #0008;white-space:normal}.timeline canvas{display:block;width:100%;height:365px}.guide canvas{display:block;width:100%;height:310px;margin-top:5px}table{width:100%;border-collapse:collapse;font-size:12px}th{color:var(--muted);font-weight:600;text-align:left;padding:8px 7px;border-bottom:1px solid var(--line)}td{padding:8px 7px;border-bottom:1px solid #29313a;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;max-width:240px}
@media(max-width:850px){.wrap{padding:12px}.summary{grid-column:span 4}.current,.preview,.guide,.timeline{grid-column:1/-1}.preview{min-height:220px}.history{overflow:auto}.top{align-items:flex-start}.brand h1{font-size:19px}.timeline canvas{height:345px}.guide canvas{height:295px}}
@media(max-width:520px){.summary{grid-column:span 6}.summary .n{font-size:23px}.card{border-radius:12px;padding:12px}.timeline canvas{height:335px}.guide canvas{height:285px}.chart-note{font-size:10px}.mini-legend{gap:8px}}
</style>
</head>
<body>
<div class="wrap">
  <div class="top"><div class="brand"><h1>QualitySessionMeter</h1><div id="sub">Waiting for N.I.N.A. session data…</div></div><div class="live"><span class="dot"></span><span id="liveText">LOCAL</span></div></div>
  <div class="grid">
    <div class="card summary"><div class="label">Captured</div><div class="n" id="captured">—</div></div>
    <div class="card summary"><div class="label">Usable</div><div class="n" id="usable">—</div></div>
    <div class="card summary"><div class="label">Rejected</div><div class="n" id="rejected">—</div></div>
    <div class="card summary"><div class="label">Acceptance</div><div class="n" id="acceptance">—</div></div>
    <div class="card summary"><div class="label">Session Q</div><div class="n" id="sessionQ">—</div></div>
    <div class="card summary"><div class="label">Confidence</div><div class="n" id="sessionC">—</div></div>

    <div class="card current">
      <div class="section-head"><div class="section-title">Current frame <span id="status" class="status">—</span></div><button class="info" data-help="Current-frame Quality is a composite display score. ACCEPT / WARNING / REJECTED is determined by the enabled hard rules, not by Quality alone. Guide RMS is calculated from guide samples belonging to this exposure. Stars Δ and Background Δ are relative to the mature rolling clean-frame baseline for the same imaging context." aria-label="Explain current frame metrics">i</button></div>
      <div class="row"><span>Quality</span><strong id="quality">—</strong></div>
      <div class="row"><span>Target / Filter</span><strong id="target">—</strong></div>
      <div class="row"><span>Exposure Guide RMS</span><strong id="rms">—</strong></div>
      <div class="row"><span>Stars Δ vs baseline</span><strong id="stars">—</strong></div>
      <div class="row"><span>Background Δ vs baseline</span><strong id="background">—</strong></div>
      <div class="row"><span>Probable cause</span><strong id="cause">—</strong></div>
      <div class="row"><span>File</span><strong id="file">—</strong></div>
    </div>

    <div class="card preview">
      <div class="section-head"><div class="section-title">Latest LIGHT preview</div><button class="info" data-help="Display-only JPEG generated in memory from the latest saved LIGHT image. The preview never modifies the acquisition file and is not used by the quality decision engine." aria-label="Explain preview">i</button></div><div class="muted" id="previewState">Waiting for an image…</div><img id="preview" alt="Latest saved LIGHT preview">
    </div>

    <div class="card guide">
      <div class="section-head"><div class="section-title">Live guiding · rolling 20 s</div><button class="info" data-help="Upper plot: signed RA and DEC guide error around zero. Lower plot: total vector error magnitude. QSM sustained/hard excursion limits apply to total magnitude, so those thresholds are drawn only on the lower plot. The 20 s RMS here is a live diagnostic window; the Current frame Guide RMS is exposure-specific and is the value used by the exposure-RMS rule." aria-label="Explain live guiding">i</button></div>
      <div class="row"><span>20 s Total RMS</span><strong id="grms">—</strong></div>
      <div class="row"><span>20 s RA / DEC RMS</span><strong id="axes">—</strong></div>
      <div class="row"><span>20 s Max total excursion</span><strong id="gmax">—</strong></div>
      <div class="mini-legend"><span><i class="swatch" style="background:#8ab4f8"></i>RA signed error</span><span><i class="swatch" style="background:#f28b82"></i>DEC signed error</span><span><i class="swatch" style="background:#81c995"></i>Total error magnitude</span><span><i class="swatch" style="background:#fdd663"></i>Sustained threshold</span><span><i class="swatch" style="background:#ff7770"></i>Hard threshold</span></div>
      <div class="chart-wrap"><canvas id="guideCanvas"></canvas><div class="chart-tip" id="guideTip"></div></div>
    </div>

    <div class="card timeline">
      <div class="section-head"><div class="section-title">Multichannel session timeline</div><button class="info" data-help="Three independent bands: Quality/Confidence, exposure Guide RMS, and Stars/Background deltas against the rolling clean-frame baseline. Dashed colored lines are the currently configured hard limits. Red/amber vertical markers denote rejected/warning frames. G, S, B and ! identify the diagnostic cause family." aria-label="Explain multichannel timeline">i</button></div>
      <div class="chart-note">Quality + Confidence · exposure Guide RMS · image-signal deltas vs rolling clean baseline. Hover or touch for exact frame values.</div>
      <div class="chart-wrap"><canvas id="timelineCanvas"></canvas><div class="chart-tip" id="timelineTip"></div></div>
    </div>

    <div class="card history"><div class="section-head"><div class="section-title">Recent frames</div><button class="info" data-help="Newest assessed frames in this QSM session. Learning and analysis-error frames are retained for diagnosis but are not counted in the Acceptance denominator. WARNING frames are considered usable; REJECTED frames are not." aria-label="Explain recent frames">i</button></div><div style="overflow:auto"><table><thead><tr><th>#</th><th>Status</th><th>Quality</th><th>Confidence</th><th>RMS</th><th>Stars Δ</th><th>BG Δ</th><th>Filter</th><th>File</th><th>Cause</th></tr></thead><tbody id="frames"></tbody></table></div></div>

    <div class="card glossary">
      <div class="section-title">Metric definitions</div>
      <details><summary>Captured / Usable / Rejected / Acceptance</summary><p><strong>Captured</strong> is the number of QSM frame results in the current session, including LEARNING and ERROR. <strong>Usable</strong> is ACCEPTED + WARNING. <strong>Rejected</strong> means at least one enabled hard rejection rule failed. <strong>Acceptance</strong> = Usable / (Usable + Rejected); LEARNING and ERROR are deliberately excluded from that ratio.</p></details>
      <details><summary>Session Q / Confidence</summary><p><strong>Session Q</strong> is the mean Quality score of usable frames. <strong>Confidence</strong> is the mean finite confidence score of usable frames. Quality is a presentation score and never overrides an enabled hard reject rule.</p></details>
      <details><summary>Stars Δ / Background Δ</summary><p>Both are percentages relative to QSM's rolling clean-frame baseline for the same target, filter, exposure, gain, binning and camera context. Stars Δ below zero means fewer detected stars. Background Δ above zero means a brighter background; below zero means a darker background.</p></details>
      <details><summary>Network and safety model</summary><p>The Web Dashboard is read-only and is disabled by default. QSM does not open router ports, does not create a cloud account and does not send dashboard data to an external service. Optional password protection is configured in N.I.N.A. For access outside a trusted LAN, use an existing VPN or HTTPS reverse proxy rather than exposing the plain HTTP port directly to the Internet.</p></details>
    </div>
  </div>
</div>
<div class="help-pop" id="helpPop" role="status"></div>
<script>
const $=id=>document.getElementById(id);
const finite=v=>v!==null&&v!==undefined&&Number.isFinite(Number(v));
const num=(v,d=1)=>finite(v)?Number(v).toFixed(d):'—';
const pct=v=>finite(v)?num(v,1)+'%':'—';
const arc=v=>finite(v)?num(v,2)+'″':'—';
const esc=v=>String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
let lastSnapshot=null,lastTimelineGeom=null,lastGuideGeom=null;
function statusClass(v){return 'status '+String(v||'').toLowerCase().replace(/[^a-z0-9_-]+/g,'-')}
function setupCanvas(canvas){const dpr=window.devicePixelRatio||1,w=Math.max(260,canvas.clientWidth||300),h=Math.max(120,canvas.clientHeight||180);if(canvas.width!==Math.round(w*dpr)||canvas.height!==Math.round(h*dpr)){canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr)}const c=canvas.getContext('2d');c.setTransform(dpr,0,0,dpr,0,0);c.clearRect(0,0,w,h);return{c,w,h}}
function line(c,x1,y1,x2,y2,color,width=1,dash=[]){c.save();c.strokeStyle=color;c.lineWidth=width;c.setLineDash(dash);c.beginPath();c.moveTo(x1,y1);c.lineTo(x2,y2);c.stroke();c.restore()}
function text(c,value,x,y,color='#b2bbc7',size=10,weight='400',align='left'){c.save();c.fillStyle=color;c.font=`${weight} ${size}px system-ui`;c.textAlign=align;c.textBaseline='top';c.fillText(value,x,y);c.restore()}
function valueY(v,min,max,top,height){return top+height*(1-(Math.min(max,Math.max(min,Number(v)))-min)/Math.max(.000001,max-min))}
function drawPath(c,frames,getter,min,max,left,top,width,height,color,lineWidth,xGetter=null){let started=false;c.save();c.strokeStyle=color;c.lineWidth=lineWidth;c.beginPath();frames.forEach((f,i)=>{const v=getter(f);if(!finite(v)){started=false;return}const x=xGetter?xGetter(f,i):(frames.length===1?left+width/2:left+i*width/(frames.length-1)),y=valueY(v,min,max,top,height);if(!started){c.moveTo(x,y);started=true}else c.lineTo(x,y)});c.stroke();c.restore()}
function deriveCodes(f){const status=String(f?.status||'').toUpperCase();if(status==='ERROR')return'!';let t=((f?.probableCause||'')+' '+(f?.reason||'')).toUpperCase(),r='';if(/GUIDE|TRACK|WIND|RMS|EXCURSION/.test(t))r+='G';if(/STAR|CLOUD|TRANSPARENCY/.test(t))r+='S';if(/BACKGROUND|HAZE|BRIGHT SKY/.test(t))r+='B';if(status==='REJECTED'&&!r)r='?';return r}
function legend(c,x,y,maxWidth,color,name,detail){c.save();c.beginPath();c.rect(x,y-1,maxWidth,23);c.clip();c.fillStyle=color;c.beginPath();c.arc(x+5,y+6,3.2,0,Math.PI*2);c.fill();text(c,name,x+13,y,color,9,'650');text(c,detail,x+13,y+11,'#b2bbc7',8,'400');c.restore()}
function reference(c,left,width,y,color,label,bg='#11161c'){line(c,left,y,left+width,y,color,1,[5,4]);if(!label)return;c.save();c.font='600 8px system-ui';const tw=c.measureText(label).width,tx=left+width-tw-7,ty=Math.max(1,y-12);c.fillStyle=bg;c.fillRect(tx-3,ty-1,tw+6,12);text(c,label,tx,ty,color,8,'600');c.restore()}
function drawTimeline(canvas,frames,settings){const {c,w,h}=setupCanvas(canvas);const left=Math.min(215,Math.max(w<620?112:150,w*.24)),marker=36,gap=6,plotW=Math.max(1,w-left-1),bandH=Math.max(52,(h-marker-gap*2-1)/3),top=marker,rmsTop=marker+bandH+gap,imgTop=marker+2*(bandH+gap);lastTimelineGeom={left,plotW,marker,bandH,gap,w,h,frames};
 text(c,'EVENTS',3,2,'#eef2f6',9,'650');text(c,'G guide · S sky · B background · ! error',3,16,'#b2bbc7',8);legend(c,3,top+3,left-8,'#8ab4f8','Quality','0–100');legend(c,3,top+25,left-8,'#c58af9','Confidence','0–100');legend(c,3,rmsTop+5,left-8,'#81c995','Guide RMS','arcsec · lower is better');legend(c,3,imgTop+3,left-8,'#fdd663','Stars Δ',settings?.enableStarCount?`% vs baseline · reject < -${num(settings.maxStarLossPercent,1)}%`:'% vs baseline · disabled');legend(c,3,imgTop+27,left-8,'#f28b82','Background Δ',settings?.enableBackground?`limits -${num(settings.maxBackgroundDecreasePercent,1)}/+${num(settings.maxBackgroundIncreasePercent,1)}%`:'% vs baseline · disabled');
 c.save();c.beginPath();c.rect(left,0,plotW,h);c.clip();[top,rmsTop,imgTop].forEach(y=>{c.fillStyle='#11161c';c.fillRect(left,y,plotW,bandH);c.strokeStyle='#38414c';c.lineWidth=1;c.strokeRect(left+.5,y+.5,plotW-1,bandH-1);line(c,left,y+bandH/2,left+plotW,y+bandH/2,'#2c343e',1)});text(c,'100',left+plotW-29,top+2,'#b2bbc7',8);text(c,'0',left+plotW-18,top+bandH-13,'#b2bbc7',8);
 if(!frames.length){text(c,'Waiting for assessed LIGHT frames',left+plotW/2,marker+(h-marker)/2,'#b2bbc7',10,'400','center');c.restore();return}
 drawPath(c,frames,x=>x.quality,0,100,left,top,plotW,bandH,'#8ab4f8',1.8);drawPath(c,frames,x=>x.confidence,0,100,left,top,plotW,bandH,'#c58af9',1.5);
 const obsRms=Math.max(0,...frames.map(x=>finite(x.guideRmsArcsec)?Number(x.guideRmsArcsec):0));let maxRms=Math.max(2,obsRms*1.15);if(settings?.enableGuideRms&&finite(settings.maxGuideRms)&&Number(settings.maxGuideRms)>0)maxRms=Math.max(maxRms,Number(settings.maxGuideRms)*1.30);drawPath(c,frames,x=>x.guideRmsArcsec,0,maxRms,left,rmsTop,plotW,bandH,'#81c995',1.7);if(settings?.enableGuideRms&&finite(settings.maxGuideRms)){const y=valueY(settings.maxGuideRms,0,maxRms,rmsTop,bandH);reference(c,left,plotW,y,'#81c995',`RMS limit ${num(settings.maxGuideRms,2)}″`)}text(c,`0–${num(maxRms,1)}″`,left+4,rmsTop+2,'#b2bbc7',8);
 const observed=Math.max(0,...frames.flatMap(x=>[finite(x.starDeltaPercent)?Math.abs(Number(x.starDeltaPercent)):0,finite(x.backgroundDeltaPercent)?Math.abs(Number(x.backgroundDeltaPercent)):0]));const threshold=Math.max(Number(settings?.maxStarLossPercent)||0,Number(settings?.maxBackgroundIncreasePercent)||0,Number(settings?.maxBackgroundDecreasePercent)||0);const imgMax=Math.min(500,Math.max(50,observed*1.15,threshold*1.25));drawPath(c,frames,x=>x.starDeltaPercent,-imgMax,imgMax,left,imgTop,plotW,bandH,'#fdd663',1.6);drawPath(c,frames,x=>x.backgroundDeltaPercent,-imgMax,imgMax,left,imgTop,plotW,bandH,'#f28b82',1.6);reference(c,left,plotW,valueY(0,-imgMax,imgMax,imgTop,bandH),'#98a2ad','0% rolling baseline');if(settings?.enableStarCount&&finite(settings.maxStarLossPercent))reference(c,left,plotW,valueY(-Number(settings.maxStarLossPercent),-imgMax,imgMax,imgTop,bandH),'#fdd663',null);if(settings?.enableBackground){if(finite(settings.maxBackgroundIncreasePercent))reference(c,left,plotW,valueY(Number(settings.maxBackgroundIncreasePercent),-imgMax,imgMax,imgTop,bandH),'#f28b82',null);if(finite(settings.maxBackgroundDecreasePercent))reference(c,left,plotW,valueY(-Number(settings.maxBackgroundDecreasePercent),-imgMax,imgMax,imgTop,bandH),'#f28b82',null)}text(c,`±${num(imgMax,0)}%`,left+4,imgTop+2,'#b2bbc7',8);
 let badgeRight=-1e9;frames.forEach((f,i)=>{const x=frames.length===1?left+plotW/2:left+i*plotW/(frames.length-1),st=String(f.status||'').toUpperCase();if(st==='REJECTED'){c.fillStyle='#ff6e691f';c.fillRect(x-2.5,marker,5,h-marker);line(c,x,marker,x,h-1,'#ff6e69',1.5);const code=deriveCodes(f);if(code){c.font='650 9px system-ui';const bw=Math.max(17,c.measureText(code).width+8),bx=x-bw/2;if(bx>badgeRight+3){c.fillStyle='#5b2429eb';c.strokeStyle='#ff827d';c.lineWidth=.8;c.beginPath();c.roundRect(bx,3,bw,15,4);c.fill();c.stroke();text(c,code,x,5,'#fff',9,'650','center');badgeRight=bx+bw}}}else if(st==='WARNING')line(c,x,marker,x,h-1,'#fdd663',1);else if(st==='ERROR'){line(c,x,marker,x,h-1,'#ff7878',1.4);if(x-8>badgeRight+3){c.fillStyle='#5b2429eb';c.beginPath();c.roundRect(x-8,3,16,15,4);c.fill();text(c,'!',x,5,'#fff',9,'650','center');badgeRight=x+8}}});c.restore()
}
function guideTimes(items,left,width){const parsed=items.map(x=>Date.parse(x.timestampUtc)).map((v,i)=>Number.isFinite(v)?v:i);let t0=parsed[0]??0,t1=parsed[parsed.length-1]??t0;if(t1<=t0){t0=0;t1=Math.max(1,items.length-1);return{xs:items.map((_,i)=>left+(items.length===1?width/2:i*width/Math.max(1,items.length-1))),t0,t1,real:false}}return{xs:parsed.map(t=>left+(t-t0)*width/(t1-t0)),t0,t1,real:true}}
function drawGuide(canvas,g,settings){const {c,w,h}=setupCanvas(canvas),items=g?.series||[],left=54,right=12,top=24,upperH=Math.max(105,(h-88)*.60),gap=28,lowerTop=top+upperH+gap,lowerH=Math.max(54,h-lowerTop-28),plotW=Math.max(1,w-left-right);c.fillStyle='#11161c';c.fillRect(left,top,plotW,upperH);c.fillRect(left,lowerTop,plotW,lowerH);c.strokeStyle='#38414c';c.strokeRect(left+.5,top+.5,plotW-1,upperH-1);c.strokeRect(left+.5,lowerTop+.5,plotW-1,lowerH-1);text(c,'SIGNED AXIS ERROR',left,4,'#dfe5ec',9,'650');text(c,'TOTAL ERROR MAGNITUDE',left,lowerTop-18,'#dfe5ec',9,'650');
 if(!items.length){text(c,'Waiting for guide samples',left+plotW/2,top+upperH/2-6,'#b2bbc7',10,'400','center');lastGuideGeom=null;return}
 const timing=guideTimes(items,left,plotW),axisMax=Math.max(.5,...items.flatMap(x=>[Math.abs(Number(x.raArcsec)||0),Math.abs(Number(x.decArcsec)||0)]))*1.18;[-1,-.5,0,.5,1].forEach(k=>{const v=k*axisMax,y=valueY(v,-axisMax,axisMax,top,upperH);line(c,left,y,left+plotW,y,k===0?'#6e7884':'#2c343e',k===0?1.2:1);text(c,(v===0?'0':(v>0?'+':'')+num(v,1))+'″',left-6,y-6,'#b2bbc7',8,'400','right')});
 const tickCount=w<600?3:5;for(let i=0;i<tickCount;i++){const p=i/(tickCount-1),x=left+p*plotW;line(c,x,top,x,top+upperH,'#252d35',.8);line(c,x,lowerTop,x,lowerTop+lowerH,'#252d35',.8);const sec=timing.real?((timing.t0+p*(timing.t1-timing.t0)-timing.t1)/1000):(-(1-p)*(items.length-1));text(c,i===tickCount-1?'0 s':`${Math.round(sec)} s`,x,h-17,'#b2bbc7',8,'400',i===0?'left':i===tickCount-1?'right':'center')}
 drawPath(c,items,x=>x.raArcsec,-axisMax,axisMax,left,top,plotW,upperH,'#8ab4f8',1.7,(x,i)=>timing.xs[i]);drawPath(c,items,x=>x.decArcsec,-axisMax,axisMax,left,top,plotW,upperH,'#f28b82',1.7,(x,i)=>timing.xs[i]);
 const excursion=settings?.enableSustainedExcursion&&finite(settings.excursionThreshold)?Number(settings.excursionThreshold):null,hard=settings?.enableHardExcursion&&finite(settings.hardExcursionThreshold)?Number(settings.hardExcursionThreshold):null,totalMax=Math.max(1,...items.map(x=>finite(x.totalArcsec)?Number(x.totalArcsec):0),excursion||0,hard||0)*1.18;[0,.5,1].forEach(k=>{const v=k*totalMax,y=valueY(v,0,totalMax,lowerTop,lowerH);line(c,left,y,left+plotW,y,'#2c343e',1);text(c,num(v,1)+'″',left-6,y-6,'#b2bbc7',8,'400','right')});
 if(excursion!==null)reference(c,left,plotW,valueY(excursion,0,totalMax,lowerTop,lowerH),'#fdd663',`excursion ${num(excursion,2)}″`);if(hard!==null){const hy=valueY(hard,0,totalMax,lowerTop,lowerH);c.fillStyle='#f28b8214';c.fillRect(left,lowerTop,plotW,Math.max(0,hy-lowerTop));reference(c,left,plotW,hy,'#ff7770',`hard ${num(hard,2)}″`)}drawPath(c,items,x=>x.totalArcsec,0,totalMax,left,lowerTop,plotW,lowerH,'#81c995',1.8,(x,i)=>timing.xs[i]);
 lastGuideGeom={left,plotW,top,upperH,lowerTop,lowerH,w,h,items,xs:timing.xs,excursion,hard}
}
function nearestIndex(xs,x){let best=0,dist=Infinity;xs.forEach((v,i)=>{const d=Math.abs(v-x);if(d<dist){dist=d;best=i}});return best}
function timelineTip(e){const tip=$('timelineTip'),g=lastTimelineGeom;if(!g||!g.frames.length){tip.style.display='none';return}const rect=$('timelineCanvas').getBoundingClientRect(),x=e.clientX-rect.left;if(x<g.left||x>g.left+g.plotW){tip.style.display='none';return}const i=g.frames.length===1?0:Math.max(0,Math.min(g.frames.length-1,Math.round((x-g.left)/g.plotW*(g.frames.length-1)))),f=g.frames[i],cause=f.probableCause||f.reason||'';tip.innerHTML=`<strong>Frame #${esc(f.frameIndex)} · ${esc(f.status)}</strong><br>Quality ${esc(num(f.quality,0))} / 100 · Confidence ${esc(pct(f.confidence))}<br>Exposure Guide RMS ${esc(arc(f.guideRmsArcsec))}<br>Stars Δ ${esc(pct(f.starDeltaPercent))} · Background Δ ${esc(pct(f.backgroundDeltaPercent))}${cause?'<br>'+esc(cause):''}`;positionTip(tip,rect,x,e.clientY-rect.top)}
function guideTip(e){const tip=$('guideTip'),g=lastGuideGeom;if(!g||!g.items.length){tip.style.display='none';return}const rect=$('guideCanvas').getBoundingClientRect(),x=e.clientX-rect.left;if(x<g.left||x>g.left+g.plotW){tip.style.display='none';return}const i=nearestIndex(g.xs,x),s=g.items[i],total=finite(s.totalArcsec)?Number(s.totalArcsec):null,flags=[];if(g.excursion!==null&&total!==null&&total>g.excursion)flags.push('above sustained-excursion threshold');if(g.hard!==null&&total!==null&&total>=g.hard)flags.push('at/above hard-excursion threshold');const ts=s.timestampUtc?new Date(s.timestampUtc).toLocaleTimeString():'';tip.innerHTML=`<strong>${esc(ts||'Guide sample')}</strong><br>RA ${esc(arc(s.raArcsec))} · DEC ${esc(arc(s.decArcsec))}<br>Total ${esc(arc(s.totalArcsec))}${flags.length?'<br><span style="color:#fdd663">'+esc(flags.join(' · '))+'</span>':''}`;positionTip(tip,rect,x,e.clientY-rect.top)}
function positionTip(tip,rect,x,y){tip.style.display='block';tip.style.left=Math.min(Math.max(4,rect.width-354),Math.max(4,x+12))+'px';tip.style.top=Math.max(4,Math.min(rect.height-82,y-20))+'px'}
function render(s){lastSnapshot=s;const q=s.summary||{},f=s.currentFrame||{},g=s.guidingLive||{},frames=s.frames||[];$('captured').textContent=q.captured??0;$('usable').textContent=q.usable??0;$('rejected').textContent=q.rejected??0;$('acceptance').textContent=pct(q.acceptanceRate);$('sessionQ').textContent=num(q.sessionQuality,0);$('sessionC').textContent=num(q.sessionConfidence,0);$('status').textContent=f.status||'NO FRAME';$('status').className=statusClass(f.status);$('quality').textContent=finite(f.quality)?num(f.quality,0)+' / 100':'—';$('target').textContent=[f.target,f.filter].filter(Boolean).join(' · ')||'—';$('rms').textContent=arc(f.guideRmsArcsec);$('stars').textContent=pct(f.starDeltaPercent);$('background').textContent=pct(f.backgroundDeltaPercent);$('cause').textContent=f.probableCause||f.reason||'—';$('file').textContent=f.finalFileName||f.fileName||'—';$('grms').textContent=arc(g.rmsTotalArcsec);$('axes').textContent=arc(g.rmsRaArcsec)+' / '+arc(g.rmsDecArcsec);$('gmax').textContent=arc(g.maxExcursionArcsec);$('sub').textContent=(s.mode?.enabled?'QSM enabled':'QSM disabled')+' · '+(s.mode?.monitorOnly?'Monitor only':'Active file handling');$('frames').innerHTML=frames.slice().reverse().slice(0,30).map(x=>{const file=x.finalFileName||x.fileName||'',cause=x.probableCause||x.reason||'';return`<tr><td>${esc(x.frameIndex)}</td><td><span class="${statusClass(x.status)}">${esc(x.status)}</span></td><td>${esc(num(x.quality,0))}</td><td>${esc(num(x.confidence,0))}</td><td>${esc(arc(x.guideRmsArcsec))}</td><td>${esc(pct(x.starDeltaPercent))}</td><td>${esc(pct(x.backgroundDeltaPercent))}</td><td>${esc(x.filter)}</td><td title="${esc(file)}">${esc(file)}</td><td title="${esc(cause)}">${esc(cause)}</td></tr>`}).join('');drawGuide($('guideCanvas'),g,s.settings||{});drawTimeline($('timelineCanvas'),frames,s.settings||{})}
async function refresh(){try{const r=await fetch('/dashboard/api/snapshot',{cache:'no-store'});if(r.status===401){location.reload();return}if(!r.ok)throw new Error('snapshot');render(await r.json());$('liveText').textContent='LIVE'}catch{$('liveText').textContent='RECONNECTING'}}
function preview(){const img=$('preview');img.src='/dashboard/api/preview.jpg?t='+Date.now();img.onload=()=>{$('previewState').textContent='Latest saved LIGHT'};img.onerror=()=>{$('previewState').textContent='Preview not available yet'}}
function showHelp(button){const pop=$('helpPop');pop.textContent=button.dataset.help||'';const r=button.getBoundingClientRect();pop.style.display='block';const pw=Math.min(430,innerWidth-28);pop.style.width=pw+'px';pop.style.left=Math.max(14,Math.min(innerWidth-pw-14,r.left-pw/2+r.width/2))+'px';pop.style.top=Math.min(innerHeight-pop.offsetHeight-14,r.bottom+8)+'px'}
document.querySelectorAll('.info').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();showHelp(b)}));document.addEventListener('click',()=>{$('helpPop').style.display='none'});$('timelineCanvas').addEventListener('pointermove',timelineTip);$('timelineCanvas').addEventListener('pointerleave',()=>{$('timelineTip').style.display='none'});$('guideCanvas').addEventListener('pointermove',guideTip);$('guideCanvas').addEventListener('pointerleave',()=>{$('guideTip').style.display='none'});refresh();preview();setInterval(refresh,2000);setInterval(preview,5000);addEventListener('resize',()=>{if(lastSnapshot)render(lastSnapshot)});
</script>
</body>
</html>
""";
}
